name: SimpleHelpTickets
main: main.java.simplehelptickets.SimpleHelpTickets
version: 1.3.9
author: Carisus
commands:
   sht:
      aliases: [helptickets, simplehelptickets]
      description: Help Menu
      permission:
      usage: /sht
   ticket:
      aliases: [helpme, grief]
      description: Open a help ticket
      permission: ticket.ticket
      usage: /ticket <Description>
   tickets:
      description: Review your/all help tickets
      permission:
      usage: /tickets [ac]  
   ticketclose:
      aliases: [ticketcl]
      description: close or reopen a help ticket
      permission:
      usage: /ticketclose [r] <#>
   ticketreply:
      aliases: [ticketr]
      description: reply to a help ticket
      permission:
      usage: /ticketreply <#> <reply>
   tickettake:
      description: Assign self to a help ticket
      permission: ticket.admin
      usage: /tickettake <#>
   ticketcheck:
      aliases: [ticketch]
      description: check your/a help ticket
      permission:
      usage: /ticketcheck <#>
   ticketdel:
      aliases: [ticketd]
      description: Delete a ticket
      permission:
      usage: /ticketdel <#>
   ticketpurge:
      aliases: [ticketp]
      description: Purge all expired tickets
      permission: ticket.admin
      usage: /ticketpurge